### ISSUE TITLE
GraphQLSchema from graphql incompatible with GraphQLSchema from apollo-link-scalars

### ISSUE THREAD

**Issue by kenharbortech** [eturino/apollo-link-scalars#117]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[X ] question about how to use this project

* **Summary**
I am trying to [this approach](https://github.com/eturino/apollo-link-scalars#synchronously-creating-a-link-instance-with-graphql-code-generator-setup) to generate the schema for `withScalars` method from apollo-link-scalars. However, the GraphQLSchema generated from using the utility methods from graphql is not compatible with the GraphQLSchema type from apollo-link-scalars. Here is the package version I am using.
`"apollo-link": "^1.2.14",`
`"graphql": "^15.1.0",`

For the implementation I just followed the approach to generate the schema.
```const schema = buildClientSchema((introspectionResult as unknown) as IntrospectionQuery)```

I notice the `graphql` package version from apollo link scalars is `"graphql": "^14.5.8",`.  
Updated: Just found this PR. https://github.com/eturino/apollo-link-scalars/pull/115 . It seems to fix the case. Do you have any plan to merge it? Thank you.

**Comment by dobrinov** [comment]
As I noted [here](https://github.com/eturino/apollo-link-scalars/pull/115#issuecomment-663901158), the right solution is to define graphql as a peerDependency. This way you will ensure that the package and its "host" are using the same version of a specific library.

**Comment by eturino** [comment]
@dobrinov I've merged your PR for now to unblock this issue, but I agree with you that the right approach is peer dependencies. I'll try to get to it this evening.
