### ISSUE TITLE
Network error after first GraphQL request

### ISSUE THREAD

**Issue by JakubPetriska** [eturino/apollo-link-scalars#20]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[*] question about how to use this project

* **Summary**
When I try to use the `apollo-link-scalars` as advised in the README I get following error after I try to do first GraphQL query:
```
Uncaught (in promise) Error: Network error: operation.getContext is not a function
    at new ApolloError (bundle.esm.js:76)
    at bundle.esm.js:1469
```

My apollo client setup is following:
```
const cache = new InMemoryCache()

const schemaDocument = loader('../common/schema.graphql')

const link = ApolloLink.from([
  withScalars({
    schema: buildASTSchema(schemaDocument),
    typesMap: { DateTime: GraphQLDateTime }
  }),
  new HttpLink()
])

const client = new ApolloClient({
  cache,
  link
})
```

The error disappears when the `apollo-scalars-link` is removed.

I'm have an application created by Create React App.

Let me know if there's any other information I can provide, however this is all I know right now.

**Comment by eturino** [comment]
@JakubPetriska I got that one before, and the latest release should fix it. Please let me know if it is still happening

**Comment by eturino** [comment]
for more info, it was a silly mistake in the serialization process, which replaced the original operation with a new object with the serialized variables… but it lost the prototype in the process. That meant that the `getContext` function was not there anymore. 🤦‍♂

**Comment by JakubPetriska** [comment]
This works now. Thank you very much!!!

**Comment by brabeji** [comment]
@eturino Awesome, I like this link a lot!

**Comment by eturino** [comment]
@all-contributors please add @JakubPetriska for bug

**Comment by JakubPetriska** [comment]
Wow, thanks @eturino !
