### ISSUE TITLE
Transform of nullable fields to a Maybe monad

### ISSUE THREAD

**Issue by nagirrab** [eturino/apollo-link-scalars#235]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[] question about how to use this project

* **Summary**
Hi,

We're using this project to great success for transforming some scalars like date times etc. We're also using an implementation of the Maybe monad for more functional-style access to nullable properties (https://github.com/hojberg/seidr).

We'd love to be able to automatically translate the nullable types into Maybes, so e.g. a type that looks like:

```graphql
type Name  {
  title: String
  name: String!
  suffix: String
}
```

When the server returns:

```json
  {
    "title": "Dr",
    "name": "Greg House",
   "suffix": null
 }
```

Gets transformed to

```javascript
{
    title: Just("Dr")
     name: "Greg House",
    suffix: Nothing()
 }
```
 
I appreciate that this isn't directly the purpose of this project, but given the set of tasks for schema traversal, parsing and serializing etc, I was wondering if you would have any interest in expanding the scope of the project to allow it.

The specific task would be to change the traversal so that whenever it comes across a nullable type, it runs a special serializer/parser as appropriate.

If you are interested, I'm more than happy to do the work on it. If not, I'll probably look at either forking this to allow it, or taking a lot of the structure to make a similar project that can work in tandem with this to do the transformation.

Cheers!

**Comment by eturino** [comment]
@nagirrab I don't use the Maybe monad (nor Either) on my project, but I would be more than happy to have support for it. I am a bit swamped at work to make it soonish but if you want to give it a go I'll wait for your PR with great interest :)
