### ISSUE TITLE
Compatibility problems with Metro bundler?

### ISSUE THREAD

**Issue by Alfredo-Delgado** [eturino/apollo-link-scalars#278]
**bug report**

The library (0.3.0) does not appear to be working well with [Metro bundler](https://facebook.github.io/metro/). This [line](https://github.com/eturino/apollo-link-scalars/blob/v0.x/src/lib/serializer.ts#L14)  `import { FunctionsMap, isNone, mapIfArray } from "..";` has been transpiled to `const __1 = require("..");` and  causes runtime errors as `__1` is evaluating to `undefined`.

**Comment by eturino** [comment]
@Alfredo-Delgado 

I see. I haven't used Metro bundler myself, I'm afraid.

I am quite unable to get time to fix this now, I'm afraid. A health-related family matter has me fully occupied, and it will continue to do so for the next month at least. But I will welcome a PR that adress it, if you can.

Cheers
