### ISSUE TITLE
Link isn't called on selected fields, logic unknown

### ISSUE THREAD

**Issue by JaffParker** [eturino/apollo-link-scalars#284]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

I'm using the latest to date versions of both the link and the client, but this issue existed on the old version as well.

On seemingly random occasions the link won't parse a date. My app is very heavy with dates, so that happens pretty often. Right now I'm experiencing this in a component that compares 2 dates - literally one is parsed and the other one is still a string.

I ruled out this being a cache issue since it still occurs if I make fetchPolicy: 'no-cache'. With some logging enabled I see that the date isn't even supplied to the parser. The type of the field is correct in the schema.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Apollo client v3.3.12
Apollo link scalars v2.1.1

My client setup:

```ts
import { ApolloClient, ApolloLink, InMemoryCache } from '@apollo/client'
import { withScalars } from 'apollo-link-scalars'
import { parseISO } from 'date-fns'
import { buildClientSchema, IntrospectionQuery } from 'graphql'
import result from './generated/graphql'
import introspectionResult from './generated/graphql.schema.json'
import { createHttpLink } from '@apollo/client/link/http'

export const makeApolloClient = (
  bearerToken?: string,
): ApolloClient<unknown> => {
  const schema = buildClientSchema(
    (introspectionResult as unknown) as IntrospectionQuery,
  )

  const ScalarsLink = withScalars({
    schema,
    typesMap: {
      DateTime: {
        serialize: (parsed: Date) => parsed.toISOString(),
        parseValue: (ISOstring: string | null): Date | null =>
          ISOstring ? parseISO(ISOstring) : null,
      },
    },
  })

  const HttpLink = createHttpLink({
    uri: '/graphql',
    ...(bearerToken && { headers: { Authorization: `Bearer ${bearerToken}` } }),
  })

  return new ApolloClient({
    link: ApolloLink.from([ScalarsLink, HttpLink]),
    cache: new InMemoryCache({
      ...result,
    }),
  })
}
```

As you see, I removed all other 3rd party links, the issue still persists

**Comment by eturino** [comment]
I haven't encountered this in my application, and I have very heavy use of dates as well. It is very strange.

Could you provide an example app with the schema and a response or something of the sort to try to reproduce this?

Cheers.

**Comment by JaffParker** [comment]
@eturino I'll provide an example, just got busy with work, but I noticed that this can be fixed by disabling cache in queries where it happens. I carefully read the disclaimer in the README and it looks like this could be the case of Apollo serializing the date. Do you think that could be the case?

Again, I'm preparing the example, it'll just take a little while. Threw this in just in the meantime

**Comment by eturino** [comment]
It might be the case
