### ISSUE TITLE
v0.4.0 published as latest after v2.1.2

### ISSUE THREAD

**Issue by mmende** [eturino/apollo-link-scalars#297]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

I know that not every package follows [semantic versioning](https://semver.org/), but going from v2.1.2 to v0.4.0 as latest version on npm looks like a publishing mistake to me. Was this step intended or what's the point about going down 2 major versions?

Kind regards

**Comment by eturino** [comment]
🤦 I published a hotfix version of the 0.x branch after the main branch one. So npm went nuts. I'll publish a new dummy one to fix npm this afternoon.

Thanks for this!

**Comment by mmende** [comment]
Ah ok I see... thanks for clearing this up and publishing the fix so fast
