### ISSUE TITLE
Upgrade to ApolloLink in @apollo/client/core v3?

### ISSUE THREAD

**Issue by geekox86** [eturino/apollo-link-scalars#34]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I think it is very simple and backward compatible, right?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by eturino** [comment]
I don't use v3 yet in my project, but it should be ok to make it backwards compatible. I'll have a look @geekox86

**Comment by eturino** [comment]
FYI - I am a bit swamped with work at the moment so it may take me a bit longer to get it.

**Comment by geekox86** [comment]
Do you accept a PR for it?

**Comment by eturino** [comment]
for sure!

**Comment by eturino** [comment]
of course!

**Comment by JesseZomer** [comment]
Also interested in this 👀

**Comment by eturino** [comment]
@JesseZomer yeah, very sorry about this. I've been quite swamped at work with other stuff. I hope to get into that in the next couple of weeks. I would be very grateful if anyone wants to get a PR going :)
//cc @geekox86

**Comment by JesseZomer** [comment]
Any progress? I have a branch at work waiting for this fix.

Thank you for your work 👍

**Comment by eturino** [comment]
@JesseZomer @geekox86 v1.0 with support for apollo v3 and graphql as peer dependency has been released.
