### ISSUE TITLE
Documentation Clarification: How are null values processed?

### ISSUE THREAD

**Issue by UselessPickles** [eturino/apollo-link-scalars#360]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**

The README does not currently clarify where responsibility lies for handling null values, when null values will or will not be passed to various functions, etc.. Some additional detail/clarification in the README would help in understanding exactly what needs to be handled within implementations of custom mappings and `nullFunctions`.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

The one example of a custom mapping in the README seems to contradict itself because the implementation of `serialize` does not handle null, but the implementation of `parseValue` does handle null:

```ts
const typesMap = {
  CustomScalar: {
    serialize: (parsed: CustomScalar) => parsed.toString(),
    parseValue: (raw: string | number | null): CustomScalar | null => {
      return raw ? new CustomScalar(raw) : null;
    }
  }
};
```

In addition to the contradiction between the two methods on whether null needs to be handled, it's confusing that `parseValue` is defined to handle `string` and `number` input, but `serialize` clearly returns only `string`. 

My confusion boils down to these 2 (interrelated) questions:
1. Are the parse/serialize methods of custom mappings responsible for handling null values for fields that are declared as nullable in the graphql schema? 
2. What are the interactions between the custom mapping functions and the `nullFunctions` implementation? For example, what is the order in which they are called, and under which conditions? Are values always unconditionally passed through both the `nullFunctions` and custom mapping functions in both directions (serialize and parse), or does `apollo-link-scalars` do some null/undefined detection handling along the way to bypass certain steps and simplify what needs to be handled within the custom functions?

A detailed explanation of how values are processed in both directions would probably help clarify this.

**Comment by eturino** [comment]
You are right, it is not obvious.
`CustomScalar.parseValue()` is not intended to deal with `null`s. In fact, it is not invoked if the value is `null` or `undefined`. I'll make a note about changing the types and clarifying in the README.

Regarding the `nullFunctions`, **they are called at the end, after the rest of the serialization/parsing is being done**. They can receive nulls, and it's intended to be for wrapping values and/or deal with nulls in a different way.

For example, you could have a nullFunction that parses all nulls as an instance of a class EmptyValue.

```ts
  parseValue(raw: any) {
    if (isNone(raw)) {
      return new Empty();
    }
    
    return raw;
  }
```

**Comment by UselessPickles** [comment]
@eturino Thanks for the explanation.

So this means that the example in README should be simplified to:
```
const typesMap = {
  CustomScalar: {
    serialize: (parsed: CustomScalar) => parsed.toString(),
    parseValue: (raw: string): CustomScalar | null => {
      // NOTE: empty string is being treated as null
      return raw ? new CustomScalar(raw) : null;
    }
  }
};
```

`parseValue` should only ever receive a `string` (that is the "raw" data type of the graphql scalar), and the conditional in there is to handle empty strings rather than null.

**Comment by eturino** [comment]
@all-contributors please add @nagirrab for doc

**Comment by eturino** [comment]
@all-contributors please add @UselessPickles for doc

**Comment by eturino** [comment]
I just pushed a change in the README. Thanks!
