### ISSUE TITLE
Scalars not parsed when fragment spreading causes a field to appear multiple times

### ISSUE THREAD

**Issue by floriancargoet** [eturino/apollo-link-scalars#370]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
`fragmentReducer()` returns an incorrect result when there are multiple occurrences of the same field. The last occurence of a field should overwrite the previous ones but it's not the case. When this happens, the `selections` are wrong and some scalar fields may not be parsed (because they are incorrectly excluded from the selections).

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Here's an example:
```
query MyQuery {
  someField {
    ...FragmentA,
    subFieldB { // should overwrite subFieldB from FragmentA
      ...FragmentB
    }
  }
}

fragment FragmentA on A {
  fieldA1
  fieldA2
  fieldA3
  subFieldB {
    fieldB2
  }
}

fragment FragmentB on B {
  fieldB1
  fieldB2
  fieldB3
}
```

I expect `fragmentReducer()` to resolve the query to:
```
query MyQuery {
  someField {
    fieldA1
    fieldA2
    fieldA3
    subFieldB {
      fieldB1
      fieldB2
      fieldB3
    }
  }
}
```
But instead it is: 
```
query MyQuery {
  someField {
    fieldA1
    fieldA2
    fieldA3
    subFieldB {
      fieldB2
    }
  }
}
```

**Now the result is that if `fieldB1` or `fieldB3` are custom scalars, they are ignored by `parser.parseObjectWithSelections(data, rootType, rootSelections);` and are not converted at all.**

In this specific example, I believe the problem comes from `uniqueNodes()` in `fragment-utils.ts`. Before calling this function, all the fields are still there (subFieldB is there twice) but `uniqueNodes()` keeps the first occurence instead of the last one.

**Comment by eturino** [comment]
understood. Good catch @floriancargoet. I'll have a look this weekend and let you know when I have a fix.

Thanks!

**Comment by eturino** [comment]
@all-contributors please add @floriancargoet with bug

**Comment by eturino** [comment]
new version with the fix @floriancargoet. Please have a look. Reopen this is if there are more problems with this, please.

Thanks!
