### ISSUE TITLE
Fields might get passed to `parseValue` more than once

### ISSUE THREAD

**Issue by QiroNT** [eturino/apollo-link-scalars#545]
### **I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository
- [ ] question about how to use this project

### **Summary**

Follow up to #370, `fieldB2` now gets passed into `parseValue` twice, which I think is not intended.

Changing the `parseValue` of `Date` inside the test to `(typeof raw === 'string' ? new Date(raw) : null)` reveals the issue.

### **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

`treatSelection` should have some way to make sure a field is only being parsed once, or a new implementation is needed.

**Comment by floriancargoet** [comment]
@eturino I see your tests in `inline-fragments.spec.ts` include `if (raw instanceof Date) return raw;` to prevent from double parsing. Is this the expected way to writer custom scalar parsers? Or should we open an issue and try to prevent this double parsing from happening in the first place?

**Comment by eturino** [comment]
@floriancargoet that's how I have mine at work, but it would be great to figure out a way to prevent this if possible. Please open an issue and let's work on it.
As a disclaimer, I have very very little bandwidth these days I'm afraid, so I don't know when I'll be able to pick it up. Help is most welcome! :)

**Comment by floriancargoet** [comment]
I got bit by this bug again so this time I'm opening an issue :-)
